Resources
| where type in~ (
  'microsoft.web/sites',
  'microsoft.web/serverfarms',
  'microsoft.insights/components',
  'microsoft.managedidentity/userassignedidentities',
  'microsoft.app/containerapps',
  'microsoft.app/managedenvironments',
  'microsoft.containerservice/managedclusters',
  'microsoft.compute/virtualmachines',
  'microsoft.compute/virtualmachinescalesets',
  'microsoft.containerregistry/registries'
)
| project name, type, resourceGroup, subscriptionId, location, id, tags
| order by type asc, name asc
