Resources
| where type in~ (
  'microsoft.network/virtualnetworks',
  'microsoft.network/networksecuritygroups',
  'microsoft.network/publicipaddresses',
  'microsoft.network/networkinterfaces',
  'microsoft.network/loadbalancers',
  'microsoft.network/routetables',
  'microsoft.network/virtualnetworkgateways',
  'microsoft.network/privateDnsZones',
  'microsoft.network/dnszones',
  'microsoft.network/bastionhosts',
  'microsoft.network/natgateways',
  'microsoft.network/frontdoors'
)
| project name, type, resourceGroup, subscriptionId, location, id, tags
| order by type asc, name asc
